# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: "./windows/testapp.sln"
  buildPlatforms: "x64"
  buildConfiguration: "Release"
  appxPackageDir: '$(build.artifactStagingDirectory)\AppxPackages\\'

steps:
- task: NuGetToolInstaller@1

- task: UseNode@1
  inputs:
    version: "14.17.0"

- script: |
    cd $(appPath)
    npx react-native autolink-windows --check
  displayName: Check React-Native Autolink-Windows

- script: choco install windows-sdk-10-version-1903-all --force -y
  displayName: Install Windows SDK

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: "$(solution)"
    msbuildArgs: '/p:AppxBundlePlatforms="$(buildPlatform)" 
                  /p:platform=x64 /p:AppxPackageDir="$(appxPackageDir)" 
                  /p:AppxBundle=Always 
                  /p:UapAppxPackageBuildMode=SideloadOnly 
                  /p:AppxPackageSigningEnabled=false 
                  /p:PackageCertificateThumbprint="" 
                  /p:PackageCertificateKeyFile="./windows/testapp_TemporaryKey.pfx" 
                  /v:diag 
                  /bl:$(build.artifactStagingDirectory)\$(Build.BuildNumber).binlog'
    platform: "x86"
    configuration: "$(buildConfiguration)"

- task: PublishBuildArtifacts@1
  condition: always()
  displayName: Publish MSBuild logs
  inputs:
    PathtoPublish: $(build.artifactStagingDirectory)\$(Build.BuildNumber).binlog
    ArtifactName: $(Build.BuildNumber).binlog